import { test, expect } from '@playwright/test';
import { faker } from '@faker-js/faker';


test('test', async ({ page }) => {

  //method to auto fill dummy names
  const lastName = faker.person.lastName();
  const firstName = faker.person.firstName();
  const middleInitial = faker.string.alpha({ length: 1 }).toUpperCase();
  const email = faker.internet.email({ firstName, lastName });

  //Test steps
  //dev
  await page.goto('https://dev.heims.ph/admission');

  //await page.getByRole('button', { name: 'Submit Form' }).click();
  await page.locator('div').filter({ hasText: /^Freshmen$/ }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill(lastName);
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill(firstName);
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill(middleInitial);
  await page.locator('#civil_status').click();
  await page.getByRole('option', { name: 'Single' }).click();
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.getByText('12345678910111213141516171819202122232425262728293031').click();
  await page.getByRole('textbox', { name: 'Place of Birth' }).click();
  await page.getByRole('textbox', { name: 'Place of Birth' }).fill('a');
  await page.getByRole('radio', { name: 'Male', exact: true }).check();
  await page.getByRole('textbox', { name: 'Religion' }).click();
  await page.getByRole('textbox', { name: 'Religion' }).fill('N/A');
  await page.getByText('GenderMaleFemaleReligionEthnic AffiliationNationality').click();
  await page.getByRole('textbox', { name: 'Ethnic Affiliation' }).click();
  await page.getByRole('textbox', { name: 'Ethnic Affiliation' }).fill('N/A');
  await page.getByRole('textbox', { name: 'Nationality' }).click();
  await page.getByRole('textbox', { name: 'Nationality' }).fill('Filipino');
  await page.locator('#region').click();
  await page.getByRole('option', { name: 'REGION XIII (Caraga)' }).click();
  await page.locator('#province').click();
  await page.getByRole('option', { name: 'SURIGAO DEL SUR' }).click();
  await page.locator('#city').click();
  await page.getByRole('option', { name: 'CITY OF TANDAG (Capital)' }).click();
  // Ensure barangay options are ready, then pick Telaje using a resilient, case-insensitive matcher
  await page.waitForTimeout(250); // small pause to allow dependent dropdown to populate
  await page.locator('#barangay').click();
  await page.getByRole('option', { name: /San Jose/i }).first().click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).fill('a');
  await page.getByRole('textbox', { name: 'Telephone Number' }).fill('09999999999');
  await page.getByRole('textbox', { name: 'Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).fill('09999999999');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill(email);
  await page.getByText('Are you solo parent?YesNo').click();
  await page.getByTestId('btn-group-containerNO').first().click();
  await page.getByTestId('btn-group-containerNO').nth(2).click();
  await page.getByTestId('btn-group-containerNO').nth(1).click();
  await page.getByTestId('btn-group-containerNO').nth(3).click();
  await page.getByTestId('btn-group-containerNO').nth(5).click();
  await page.getByTestId('btn-group-containerNO').nth(4).click();
  await page.getByText('Are you a Working Student?YesNo').click();
  await page.locator('div:nth-child(4) > .flex.flex-col > .Button_btn-group-container__COJ2I > button:nth-child(2)').click();
  await page.locator('div:nth-child(7) > .flex-grow > .flex.flex-col > .Button_btn-group-container__COJ2I > button:nth-child(2)').click();
  await page.locator('div:nth-child(9) > .flex-grow > div > .Button_btn-group-container__COJ2I > button:nth-child(2)').first().click();
  await page.locator('div:nth-child(9) > .flex-grow > div:nth-child(2) > .Button_btn-group-container__COJ2I > button:nth-child(2)').click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Add School' }).click();
  await page.getByRole('textbox', { name: 'School' }).click();
  await page.getByRole('textbox', { name: 'School' }).fill('a');
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'Alternative Learning System (' }).click();
  await page.getByRole('textbox', { name: 'Graduation Year' }).click();
  await page.getByRole('textbox', { name: 'Graduation Year' }).fill('2021');
  await page.getByRole('textbox', { name: 'GWA' }).click();
  await page.getByRole('textbox', { name: 'GWA' }).fill('90');
  await page.getByRole('textbox', { name: 'Highest Grade' }).click();
  await page.getByRole('textbox', { name: 'Highest Grade' }).fill('98');
  await page.getByRole('textbox', { name: 'Lowest Grade' }).click();
  await page.getByRole('textbox', { name: 'Lowest Grade' }).fill('96');
  await page.getByRole('button', { name: 'Add School' }).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.locator('[id="campus_(first_choice)"]').click();
  await page.getByRole('option', { name: 'Malolos' }).click();
  //await page.getByRole('option', { name: 'Campus of Balungao' }).click();
  //await page.getByLabel('', { exact: true }).click();
  await page.locator('.MuiBackdrop-root').click();
  //await page.getByLabel('', { exact: true }).click();
  await page.locator('[id="academic_program_(first_choice)"]').click();
  await page.getByText('Bachelor of Science in Information Technology').click();

  //second choice
  await page.locator('[id="campus_(second_choice)"]').click();
  await page.getByRole('option', { name: 'Campus of Balungao' }).click();
  await page.locator('[id="academic_program_(second_choice)"]').click();
  await page.getByText('Bachelor of Manual Testing').click();
  await page.getByRole('textbox', { name: 'How did you know about the' }).click();
  await page.getByRole('textbox', { name: 'How did you know about the' }).fill('a');
  await page.getByRole('textbox', { name: 'Reason for Applying' }).click();
  await page.getByRole('textbox', { name: 'Reason for Applying' }).fill('a');
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.getByRole('gridcell', { name: '9', exact: true }).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('textbox', { name: 'Last Name Last Name Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name Last Name Last Name' }).fill('a');
  await page.getByRole('textbox', { name: 'First Name First Name First' }).click();
  await page.getByRole('textbox', { name: 'First Name First Name First' }).fill('a');
  await page.getByRole('textbox', { name: 'Middle Name Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name Middle Name' }).fill('a');
  await page.getByRole('button', { name: 'Choose date' }).first().click();
  await page.getByRole('gridcell', { name: '1', exact: true }).click();
  await page.getByRole('textbox', { name: 'Contact Number Contact Number' }).click();
  await page.getByRole('textbox', { name: 'Contact Number Contact Number' }).fill('09999999999');
  await page.getByText('Last NameFirst NameMiddle').first().click();
  await page.getByRole('textbox', { name: 'Occupation Occupation' }).click();
  await page.getByRole('textbox', { name: 'Occupation Occupation' }).fill('a');
  await page.getByRole('textbox', { name: 'Monthly Income Monthly Income' }).click();
  await page.getByRole('textbox', { name: 'Monthly Income Monthly Income' }).fill('₱ 9000.00');
  await page.getByRole('textbox', { name: 'Yearly Compensation Yearly' }).click();
  await page.getByRole('textbox', { name: 'Yearly Compensation Yearly' }).fill('₱ 9000.00');
  await page.getByTestId('btn-group-containerYES').first().click();
  await page.locator('input[name="mother_last_name"]').click();
  await page.locator('input[name="mother_last_name"]').fill('a');
  await page.locator('input[name="mother_first_name"]').click();
  await page.locator('input[name="mother_first_name"]').fill('aa');
  await page.locator('input[name="mother_middle_name"]').click();
  await page.locator('input[name="mother_middle_name"]').fill('a');
  await page.locator('.flex-grow.grid.grid-cols-1.md\\:grid-cols-3.gap-2 > .MuiFormControl-root.MuiTextField-root.css-10xrl8i > .MuiInputBase-root').click();
  await page.getByRole('button', { name: 'Choose date' }).nth(1).click();
  await page.getByRole('gridcell', { name: '1', exact: true }).click();
  await page.locator('input[name="mother_contact_no"]').click();
  await page.locator('input[name="mother_contact_no"]').fill('09999999999');
  await page.locator('input[name="mother_occupation"]').click();
  await page.locator('input[name="mother_occupation"]').fill('a');
  await page.locator('input[name="mother_monthly_income"]').click();
  await page.locator('input[name="mother_monthly_income"]').fill('₱ 9000.00');
  await page.locator('input[name="mother_yearly_compensation"]').click();
  await page.locator('input[name="mother_yearly_compensation"]').fill('₱ 9000.00');
  await page.getByTestId('btn-group-containerYES').nth(1).click();
  await page.locator('input[name="guardian_last_name"]').click();
  await page.locator('input[name="guardian_last_name"]').fill('a');
  await page.locator('input[name="guardian_first_name"]').click();
  await page.locator('input[name="guardian_first_name"]').fill('a');
  await page.locator('input[name="guardian_middle_name"]').click();
  await page.locator('input[name="guardian_middle_name"]').fill('a');
  await page.getByRole('button', { name: 'Choose date', exact: true }).click();
  await page.getByRole('gridcell', { name: '1', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).fill('a');
  await page.getByRole('textbox', { name: 'Telephone Number Telephone' }).click();
  await page.getByRole('textbox', { name: 'Telephone Number Telephone' }).fill('a');
  await page.getByRole('textbox', { name: 'Mobile Number Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number Mobile Number' }).fill('0999999999');
  await page.getByRole('textbox', { name: 'Email Address Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address Email Address' }).fill('sasa@gmail.com');
  await page.getByRole('textbox', { name: 'Nature of Business' }).click();
  await page.getByRole('textbox', { name: 'Nature of Business' }).fill('a');
  await page.locator('input[name="guardian_monthly_income"]').click();
  await page.locator('input[name="guardian_monthly_income"]').fill('₱ 9000.00');
  await page.getByText('Last NameFirst NameMiddle NameDate of BirthAddressTelephone NumberMobile').click();
  await page.getByRole('textbox', { name: 'Other Source of Revenue' }).click();
  await page.getByRole('textbox', { name: 'Other Source of Revenue' }).fill('₱ 900.00');
  await page.getByTestId('btn-group-containerYES').nth(2).click();
  await page.getByRole('textbox', { name: 'Complete Name' }).click();
  await page.getByRole('textbox', { name: 'Complete Name' }).fill('a');
  await page.getByRole('textbox', { name: 'Complete Address' }).click();
  await page.getByRole('textbox', { name: 'Complete Address' }).fill('a');
  await page.locator('input[name="ec_person_phone_number"]').click();
  await page.locator('input[name="ec_person_phone_number"]').fill('a');
  await page.locator('input[name="ec_person_mobile_number"]').click();
  await page.locator('input[name="ec_person_mobile_number"]').fill('0999999999');
  await page.locator('input[name="ec_person_email_address"]').click();
  await page.locator('input[name="ec_person_email_address"]').fill('sample@gmail.com');
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('radio', { name: 'I consent to the University Infirmary providing medical treatment in case of' }).check();
  await page.getByRole('radio', { name: 'I consent to the University Infirmary giving medications appropriate for my' }).check();
  await page.getByRole('radio', { name: 'No Yes' }).first().check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(1).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(2).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(3).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(4).check();
  await page.getByTestId('btn-group-containerNO').first().click();
  await page.getByTestId('btn-group-containerNO').nth(1).click();
  await page.getByTestId('btn-group-containerNO').nth(2).click();
  await page.locator('div').filter({ hasText: /^Spontaneous$/ }).click();
  await page.getByText('SpontaneousNumber of times').click();
  await page.getByRole('spinbutton', { name: 'Number of times' }).fill('1');
  await page.getByTestId('btn-group-containerNO').nth(3).click();
  await page.getByTestId('btn-group-containerYES').nth(3).click();
  await page.getByRole('radio', { name: 'No Yes' }).nth(5).check();
  await page.locator('#do_alcohol').first().check();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Browse' }).click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Submit Application' }).click();
  await page.getByRole('button', { name: 'Submit Form' }).click();
});