import { test, expect } from '@playwright/test';
import { faker } from '@faker-js/faker';

for (let i = 1; i <=10; i++) {
test(`Test Applicant ${i}`, async ({ page })=> {

  //method to auto fill dummy names
  const lastName = faker.person.lastName();
  const firstName = faker.person.firstName();
  const middleInitial = faker.string.alpha({ length: 1 }).toUpperCase();
  const email = faker.internet.email({ firstName, lastName });

  await page.goto('https://bulsu-staging.heims.ph/admission');
  await page.locator('div').filter({ hasText: /^College of Medicine$/ }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill(lastName);
  await page.locator('div:nth-child(2) > .MuiInputBase-root').first().click();
  await page.getByRole('textbox', { name: 'First Name' }).fill(firstName);
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill(middleInitial);
  await page.locator('#civil_status').click();
  await page.getByRole('option', { name: 'Single' }).click();
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.getByRole('columnheader', { name: 'Monday' }).click();
  await page.getByRole('gridcell', { name: '2', exact: true }).click();
  await page.getByRole('textbox', { name: 'Place of Birth' }).click();
  await page.getByRole('textbox', { name: 'Place of Birth' }).fill('asd');
  await page.getByText('Male', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Religion' }).click();
  await page.getByRole('textbox', { name: 'Religion' }).fill('Catholic');
  await page.getByRole('textbox', { name: 'Ethnic Affiliation' }).click();
  await page.getByRole('textbox', { name: 'Ethnic Affiliation' }).fill('Sample');
  await page.getByRole('textbox', { name: 'Nationality' }).click();
  await page.getByRole('textbox', { name: 'Nationality' }).fill('Filipino');
  await page.locator('#region').click();
  await page.getByRole('option', { name: 'REGION XIII (Caraga)' }).click();
  await page.locator('#province').click();
  await page.getByRole('option', { name: 'DINAGAT ISLANDS' }).click();
  await page.locator('#city').click();
  await page.getByRole('option').first().click();
  await page.getByRole('option', { name: 'TUBAJON' }).click();
  await page.getByText('RegionREGION XIII (Caraga)ProvinceDINAGAT ISLANDSCityTUBAJONBarangayAddress').click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'Santa Cruz (Pob.)' }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).fill('Sample Address 123');
  await page.getByRole('textbox', { name: 'Telephone Number' }).click();
  await page.getByRole('textbox', { name: 'Telephone Number' }).fill('09909090909');
  await page.getByRole('textbox', { name: 'Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).fill('09909090909');
  await page.getByText('Telephone NumberMobile').click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill(email);
  await page.getByTestId('btn-group-containerNO').first().click();
  await page.getByTestId('btn-group-containerNO').nth(2).click();
  await page.getByTestId('btn-group-containerNO').nth(3).click();
  await page.getByTestId('btn-group-containerNO').nth(5).click();
  await page.locator('div:nth-child(7) > .flex-grow > .flex.flex-col > .Button_btn-group-container__COJ2I > button:nth-child(2)').click();
  await page.locator('div:nth-child(9) > .flex-grow > div > .Button_btn-group-container__COJ2I > button:nth-child(2)').first().click();
  await page.getByText('Are you child of a solo parent?YesNo').click();
  await page.getByTestId('btn-group-containerNO').nth(1).click();
  await page.getByTestId('btn-group-containerNO').nth(4).click();
  await page.locator('div:nth-child(4) > .flex.flex-col > .Button_btn-group-container__COJ2I > button:nth-child(2)').click();
  await page.locator('div:nth-child(9) > .flex-grow > div:nth-child(2) > .Button_btn-group-container__COJ2I > button:nth-child(2)').click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.locator('#academic_program').click();
  await page.getByTestId('menu-item').click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: '1st Year' }).click();
  await page.getByRole('textbox', { name: 'How did you know about the' }).click();
  await page.getByRole('textbox', { name: 'How did you know about the' }).fill('a');
  await page.getByRole('textbox', { name: 'Reason for Applying' }).click();
  await page.getByRole('textbox', { name: 'Reason for Applying' }).fill('a');
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.getByRole('gridcell', { name: '8', exact: true }).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('textbox', { name: 'NMAT Application Number' }).click();
  await page.getByRole('textbox', { name: 'NMAT Application Number' }).fill('12345');
  await page.getByRole('button', { name: 'Add School' }).click();
  await page.getByRole('textbox', { name: 'School Name' }).click();
  await page.getByRole('textbox', { name: 'School Name' }).fill('Sample school');
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'Bachelor Degree' }).click();
  await page.getByRole('textbox', { name: 'Program' }).click();
  await page.getByRole('textbox', { name: 'Program' }).fill('BSIT');
  await page.locator('div:nth-child(4) > .MuiInputBase-root').click();
  await page.getByRole('textbox', { name: 'Graduation Year' }).fill('2021');
  await page.getByText('School NameEducational').click();
  await page.getByRole('textbox', { name: 'GWA' }).click();
  await page.getByRole('textbox', { name: 'GWA' }).fill('84');
  await page.getByRole('textbox', { name: 'Awards' }).click();
  await page.getByRole('textbox', { name: 'Awards' }).fill('sample awards');
  await page.getByRole('button', { name: 'Add School' }).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('textbox', { name: 'Last Name Last Name Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name Last Name Last Name' }).fill('aa');
  await page.getByRole('textbox', { name: 'First Name First Name First' }).click();
  await page.getByRole('textbox', { name: 'First Name First Name First' }).click();
  await page.getByRole('textbox', { name: 'First Name First Name First' }).fill('a');
  await page.getByText('Last NameFirst NameMiddle').first().click();
  await page.getByRole('textbox', { name: 'Middle Name Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name Middle Name' }).fill('a');
  await page.getByRole('button', { name: 'Choose date' }).first().click();
  await page.waitForTimeout(200);
  await page.getByRole('gridcell', { name: '10', exact: true }).click();
  await page.getByRole('textbox', { name: 'Contact Number Contact Number' }).click();
  await page.getByRole('textbox', { name: 'Contact Number Contact Number' }).fill('09999999999');
  await page.getByRole('textbox', { name: 'Occupation Occupation' }).click();
  await page.getByRole('textbox', { name: 'Occupation Occupation' }).fill('occ');
  await page.getByRole('textbox', { name: 'Monthly Income Monthly Income' }).click();
  await page.getByRole('textbox', { name: 'Monthly Income Monthly Income' }).fill('₱ 1,0000.00');
  await page.getByRole('textbox', { name: 'Yearly Compensation Yearly' }).click();
  await page.getByRole('textbox', { name: 'Yearly Compensation Yearly' }).fill('₱ 10,0000.00');
  await page.getByTestId('btn-group-containerYES').first().click();
  await page.locator('input[name="mother_last_name"]').click();
  await page.locator('input[name="mother_last_name"]').fill('aa');
  await page.locator('input[name="mother_first_name"]').click();
  await page.locator('input[name="mother_middle_name"]').click();
  await page.locator('input[name="mother_middle_name"]').fill('a');
  await page.locator('input[name="mother_first_name"]').click();
  await page.locator('input[name="mother_first_name"]').fill('a');
  await page.locator('.flex-grow.grid.grid-cols-1.md\\:grid-cols-3.gap-2 > .MuiFormControl-root.MuiTextField-root.css-10xrl8i > .MuiInputBase-root').click();
  await page.getByRole('button', { name: 'Choose date' }).nth(1).click();
  await page.getByRole('gridcell', { name: '5', exact: true }).click();
  await page.getByText('Last NameFirst NameMiddle').nth(1).click();
  await page.locator('input[name="mother_contact_no"]').click();
  await page.locator('input[name="mother_contact_no"]').fill('09999999999');
  await page.locator('input[name="mother_occupation"]').click();
  await page.locator('input[name="mother_occupation"]').fill('occ');
  await page.locator('input[name="mother_monthly_income"]').click();
  await page.locator('input[name="mother_monthly_income"]').fill('₱ 5,5000.00');
  await page.locator('input[name="mother_yearly_compensation"]').click();
  await page.locator('input[name="mother_yearly_compensation"]').fill('₱ 5,0000.00');
  await page.getByTestId('btn-group-containerYES').nth(1).click();
  await page.locator('input[name="guardian_last_name"]').click();
  await page.locator('input[name="guardian_last_name"]').fill('a');
  await page.locator('input[name="guardian_first_name"]').click();
  await page.locator('input[name="guardian_first_name"]').fill('a');
  await page.locator('input[name="guardian_middle_name"]').click();
  await page.locator('input[name="guardian_middle_name"]').fill('a');

  await page.waitForLoadState('networkidle');
  await page.getByRole('button', { name: 'Choose date' }).nth(2).click();
  //await page.waitForTimeout(3000);
  await page.getByRole('gridcell', { name: '27' }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).fill('123');
  await page.getByRole('textbox', { name: 'Telephone Number Telephone' }).click();
  await page.getByRole('textbox', { name: 'Telephone Number Telephone' }).fill('099999999999');
  await page.getByText('Last NameFirst NameMiddle NameDate of BirthAddressTelephone NumberMobile').click();
  await page.getByRole('textbox', { name: 'Mobile Number Mobile Number' }).fill('09999999999');
  await page.getByRole('textbox', { name: 'Email Address Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address Email Address' }).fill('sampleqwe@gmail.com');
  await page.getByRole('textbox', { name: 'Nature of Business' }).click();
  await page.getByRole('textbox', { name: 'Nature of Business' }).fill('asd');
  await page.locator('input[name="guardian_monthly_income"]').click();
  await page.locator('input[name="guardian_monthly_income"]').fill('₱ 1,0000.00');
  await page.getByRole('textbox', { name: 'Other Source of Revenue' }).click();
  await page.getByRole('textbox', { name: 'Other Source of Revenue' }).fill('₱ 1,0000.00');
  await page.getByTestId('btn-group-containerYES').nth(2).click();
  await page.getByRole('textbox', { name: 'Complete Name' }).click();
  await page.getByRole('textbox', { name: 'Complete Name' }).fill('a');
  await page.getByRole('textbox', { name: 'Complete Address' }).click();
  await page.getByRole('textbox', { name: 'Complete Address' }).fill('a');
  await page.locator('.flex > div > .MuiInputBase-root').first().click();
  await page.locator('input[name="ec_person_phone_number"]').fill('0999999999');
  await page.locator('input[name="ec_person_mobile_number"]').click();
  await page.locator('input[name="ec_person_mobile_number"]').fill('09999999999');
  await page.locator('input[name="ec_person_email_address"]').click();
  await page.locator('input[name="ec_person_email_address"]').fill('sampe12@gmail.com');
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('radio', { name: 'I consent to the University Infirmary providing medical treatment in case of' }).check();
  await page.getByRole('radio', { name: 'I consent to the University Infirmary giving medications appropriate for my' }).check();
  await page.getByRole('radio', { name: 'No Yes' }).first().check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(1).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(2).check();
  await page.getByText('No').nth(5).click();
  await page.getByRole('radio', { name: 'No Yes' }).nth(3).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(4).check();
  await page.getByTestId('btn-group-containerYES').nth(3).click();
  await page.getByText('Do you smoke?NoYesNumber of').click();
  await page.getByRole('radio', { name: 'No Yes' }).nth(5).check();
  await page.locator('#do_alcohol').first().check();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Browse' }).click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Submit Application' }).click();
  await page.getByRole('button', { name: 'Submit Form' }).click();

  await page.waitForTimeout(5000);
  console.log(`✓ Applicant ${i} submitted successfully: ${firstName} ${lastName}`);
});
}