import { test, expect } from '@playwright/test';
import { faker } from '@faker-js/faker';
import { emit } from 'process';

test('test', async ({ page }) => {


  //method to auto fill dummy names
  const lastName = faker.person.lastName();
  const firstName = faker.person.firstName();
  const middleInitial = faker.string.alpha({ length: 1 }).toUpperCase();
  const email = faker.internet.email({ firstName, lastName });

  await page.goto('https://bulsu-staging.heims.ph/admission');
  await page.locator('div').filter({ hasText: /^CPE \(Certificate in Physical Education\)$/ }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill(lastName);
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill(firstName);
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill(middleInitial);
  await page.locator('#civil_status').click();
  await page.getByRole('option', { name: 'Single' }).click();
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.getByRole('gridcell', { name: '28' }).click();
  await page.getByRole('textbox', { name: 'Place of Birth' }).click();
  await page.getByRole('textbox', { name: 'Place of Birth' }).fill('Malolos');
  await page.locator('div').filter({ hasText: /^Male$/ }).click();
  await page.getByText('GenderMaleFemaleReligionEthnic AffiliationNationality').click();
  await page.getByRole('textbox', { name: 'Religion' }).click();
  await page.getByRole('textbox', { name: 'Religion' }).fill('Catholic');
  await page.getByRole('textbox', { name: 'Nationality' }).click();
  await page.getByRole('textbox', { name: 'Nationality' }).fill('Filipino');
  await page.locator('#region').click();
  await page.getByRole('option', { name: 'REGION XIII (Caraga)' }).click();
  await page.locator('#province').click();
  await page.getByRole('option', { name: 'DINAGAT ISLANDS' }).click();
  await page.locator('#city').click();
  await page.getByRole('option').first().click();
  await page.getByRole('option', { name: 'TUBAJON' }).click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'Santa Cruz (Pob.)' }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).fill('sample address');
  await page.getByRole('textbox', { name: 'Telephone Number' }).click();
  await page.getByRole('textbox', { name: 'Telephone Number' }).fill('09999999999');
  await page.getByRole('textbox', { name: 'Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).fill('09999999999');
  await page.getByText('Telephone NumberMobile').click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill(email);
  await page.getByTestId('btn-group-containerNO').first().click();
  await page.getByText('Are you solo parent?YesNoAre').click();
  await page.getByTestId('btn-group-containerNO').nth(3).click();
  await page.getByTestId('btn-group-containerNO').nth(2).click();
  await page.getByTestId('btn-group-containerNO').nth(1).click();
  await page.getByTestId('btn-group-containerNO').nth(4).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.locator('#program').click();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.getByRole('gridcell', { name: '27', exact: true }).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Add School' }).click();
  await page.locator('.MuiInputBase-root').first().click();
  await page.getByRole('textbox', { name: 'School Name' }).fill('Sample School');
  await page.getByText('School NameEducational').click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'Master Degree' }).click();
  await page.getByRole('textbox', { name: 'Program' }).click();
  await page.getByRole('textbox', { name: 'Program' }).fill('Sample Programs');
  await page.getByRole('textbox', { name: 'Graduation Year' }).click();
  await page.getByRole('textbox', { name: 'Graduation Year' }).fill('2021');
  await page.getByRole('textbox', { name: 'GWA' }).click();
  await page.getByRole('textbox', { name: 'GWA' }).fill('90');
  await page.getByRole('button', { name: 'Add School' }).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('textbox', { name: 'Complete Name' }).click();
  await page.getByRole('textbox', { name: 'Complete Name' }).fill('Emergency name');
  await page.getByRole('textbox', { name: 'Complete Address' }).click();
  await page.getByRole('textbox', { name: 'Complete Address' }).fill('complete address');
  await page.getByRole('textbox', { name: 'Telephone Number' }).click();
  await page.getByRole('textbox', { name: 'Telephone Number' }).fill('09999999999');
  await page.getByRole('textbox', { name: 'Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).fill('09999999999');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('sample@gmail.');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email Address' }).fill('sampleemal@gmail.');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).fill('samplemal@gmail.');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email Address' }).fill('samplemail@gmail.');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email Address' }).fill('samplemail@gmail.com');
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('radio', { name: 'I consent to the University Infirmary providing medical treatment in case of' }).check();
  await page.getByText('Medical RecordsConsent for').click();
  await page.locator('div').filter({ hasText: /^No$/ }).first().click();
  await page.getByRole('radio', { name: 'No Yes' }).first().check();
  await page.locator('div').filter({ hasText: /^No$/ }).nth(1).click();
  await page.getByRole('radio', { name: 'No Yes' }).nth(1).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(2).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(3).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(4).check();
  await page.getByTestId('btn-group-containerYES').nth(3).click();
  await page.getByRole('radio', { name: 'No Yes' }).nth(5).check();
  await page.locator('#do_alcohol').first().check();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/OIP.jpeg');
  await page.getByRole('button', { name: 'Submit Application' }).click();
  await page.getByRole('button', { name: 'Submit Form' }).click();

  await page.waitForTimeout(3000);
  console.log(`✓ Applicant submitted successfully: ${firstName} ${lastName}`);
});