import { test, expect } from '@playwright/test';
import { faker } from '@faker-js/faker';

test('test', async ({ page }) => {

  //method to auto fill dummy names
  const lastName = faker.person.lastName();
  const firstName = faker.person.firstName();
  const middleInitial = faker.string.alpha({ length: 1 }).toUpperCase();
  const email = faker.internet.email({ firstName, lastName });

  await page.goto('https://dev.heims.ph/admission');
  await page.locator('div').filter({ hasText: /^Grade 7$/ }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill(lastName);
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill(firstName);
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill(middleInitial);
  await page.locator('#civil_status').click();
  await page.getByRole('option', { name: 'Married' }).click();
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.getByRole('gridcell', { name: '5', exact: true }).click();
  await page.getByRole('textbox', { name: 'Place of Birth' }).click();
  await page.getByRole('textbox', { name: 'Place of Birth' }).fill('2021');
  await page.getByText('Male', { exact: true }).click();
  await page.locator('.grid.grid-cols-1.md\\:grid-cols-3 > div:nth-child(2) > .MuiInputBase-root').click();
  await page.getByRole('textbox', { name: 'Religion' }).fill('catholic');
  await page.getByRole('textbox', { name: 'Nationality' }).click();
  await page.getByRole('textbox', { name: 'Nationality' }).fill('FIlipino');
  await page.locator('#region').click();
  await page.getByRole('option', { name: 'REGION XIII (Caraga)' }).click();
  await page.locator('#province').click();
  await page.getByRole('option', { name: 'DINAGAT ISLANDS' }).click();
  await page.locator('#city').click();
  await page.getByRole('option', { name: 'TUBAJON' }).click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'Santa Cruz (Pob.)' }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).fill('sample address');
  await page.getByRole('textbox', { name: 'Telephone Number' }).click();
  await page.getByRole('textbox', { name: 'Telephone Number' }).fill('09999999999');
  await page.getByRole('textbox', { name: 'Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).fill('09999999999');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill(email);
  await page.getByTestId('btn-group-containerNO').first().click();
  await page.getByTestId('btn-group-containerNO').nth(2).click();
  await page.getByTestId('btn-group-containerNO').nth(3).click();
  await page.getByTestId('btn-group-containerNO').nth(5).click();
  await page.locator('div:nth-child(8) > .flex-grow > div > .Button_btn-group-container__COJ2I > button:nth-child(2)').first().click();
  await page.getByTestId('btn-group-containerNO').nth(1).click();
  await page.getByTestId('btn-group-containerNO').nth(4).click();
  await page.locator('div:nth-child(4) > .flex.flex-col > .Button_btn-group-container__COJ2I > button:nth-child(2)').click();
  await page.locator('div:nth-child(8) > .flex-grow > div:nth-child(2) > .Button_btn-group-container__COJ2I > button:nth-child(2)').click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Add School' }).click();
  await page.getByRole('textbox', { name: 'School Name School Name' }).click();
  await page.getByRole('textbox', { name: 'School Name School Name' }).fill('Binangonan Elementary School');
  await page.getByRole('textbox', { name: 'Graduation Year Graduation' }).click();
  await page.getByRole('textbox', { name: 'Graduation Year Graduation' }).fill('2021');
  await page.getByRole('textbox', { name: 'GWA GWA GWA' }).click();
  await page.getByRole('textbox', { name: 'GWA GWA GWA' }).fill('89');
  await page.getByRole('textbox', { name: 'Highest Grade Highest Grade' }).click();
  await page.getByRole('textbox', { name: 'Highest Grade Highest Grade' }).fill('88');
  await page.getByRole('textbox', { name: 'Lowest Grade Lowest Grade' }).click();
  await page.getByRole('textbox', { name: 'Lowest Grade Lowest Grade' }).fill('85');
  await page.getByRole('button', { name: 'Add School' }).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.locator('#lab_high_program').click();
  await page.getByText('Regular Class').click();
  await page.getByRole('textbox', { name: 'How did you know about the' }).click();
  await page.getByRole('textbox', { name: 'How did you know about the' }).fill('s');
  await page.getByRole('textbox', { name: 'Reason for Applying' }).click();
  await page.getByRole('textbox', { name: 'Reason for Applying' }).fill('s');
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.getByRole('gridcell', { name: '18', exact: true }).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('heading', { name: 'Father\'s Information' }).click();
  await page.getByRole('textbox', { name: 'Last Name Last Name Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name Last Name Last Name' }).fill('Dels');
  await page.getByRole('textbox', { name: 'First Name First Name First' }).click();
  await page.getByRole('textbox', { name: 'First Name First Name First' }).fill('DelsA');
  await page.getByRole('textbox', { name: 'Middle Name Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name Middle Name' }).fill('A');
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.waitForTimeout(3000);
  await page.getByRole('gridcell', { name: '1', exact: true }).click();
  await page.getByRole('textbox', { name: 'Contact Number Contact Number' }).click();
  await page.getByRole('textbox', { name: 'Contact Number Contact Number' }).fill('09999999999');
  await page.getByTestId('btn-group-containerYES').first().click();
  await page.getByText('Family InformationFather\'s').click();
  
  await page.locator('input[name="mother_last_name"]').click();
  await page.locator('input[name="mother_last_name"]').fill('Dels');
  await page.locator('input[name="mother_first_name"]').click();
  await page.locator('input[name="mother_first_name"]').fill('Sde');
  await page.locator('input[name="mother_middle_name"]').click();
  await page.locator('input[name="mother_middle_name"]').fill('A');
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.waitForTimeout(3000);
  await page.getByRole('gridcell', { name: '1', exact: true }).click();
  await page.locator('input[name="mother_contact_no"]').click();
  await page.locator('input[name="mother_contact_no"]').fill('09999999999');
  await page.getByTestId('btn-group-containerYES').nth(1).click();
  await page.locator('input[name="guardian_last_name"]').click();
  await page.locator('input[name="guardian_last_name"]').fill('aa');
  await page.locator('input[name="guardian_first_name"]').click();
  await page.locator('input[name="guardian_first_name"]').fill('a');
  await page.locator('input[name="guardian_middle_name"]').click();
  await page.locator('input[name="guardian_middle_name"]').fill('a');

  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.waitForTimeout(3000);
  await page.getByRole('gridcell', { name: '1', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).fill('as');
  await page.getByRole('textbox', { name: 'Telephone Number Telephone' }).click();
  await page.getByRole('textbox', { name: 'Telephone Number Telephone' }).fill('099999999999');
  await page.getByRole('textbox', { name: 'Mobile Number Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number Mobile Number' }).fill('09999999999');
  await page.getByRole('textbox', { name: 'Email Address Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address Email Address' }).fill('sample@gmail.com');
  await page.getByTestId('btn-group-containerYES').nth(2).click();
  await page.getByRole('textbox', { name: 'Complete Name' }).click();
  await page.getByRole('textbox', { name: 'Complete Name' }).fill('Sample');
  await page.getByRole('textbox', { name: 'Complete Address' }).click();
  await page.getByRole('textbox', { name: 'Complete Address' }).fill('Sample');
  await page.locator('input[name="ec_person_phone_number"]').click();
  await page.locator('input[name="ec_person_phone_number"]').fill('09999999999');
  await page.locator('input[name="ec_person_mobile_number"]').click();
  await page.locator('input[name="ec_person_mobile_number"]').fill('09999999999');
  await page.locator('input[name="ec_person_email_address"]').click();
  await page.locator('input[name="ec_person_email_address"]').fill('sample@gmail.com');
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('checkbox', { name: 'I voluntarily give my consent' }).check();
  await page.getByRole('checkbox', { name: 'I understand that my' }).check();
  await page.getByRole('checkbox', { name: 'None' }).check();
  await page.getByRole('radio', { name: 'No Yes' }).first().check();
  await page.getByText('Do you have any current medical condition/s?NoYesSpecify illness/esAre you').click();
  await page.getByRole('radio', { name: 'No Yes' }).nth(1).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(2).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(3).check();
  await page.locator('div').filter({ hasText: /^No$/ }).nth(4).click();
  await page.getByRole('radio', { name: 'No Yes' }).nth(4).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(5).check();
  await page.locator('#has_upcoming_surgery_or_treatment').first().check();
  await page.getByTestId('btn-group-containerNO').first().click();
  await page.getByTestId('btn-group-containerNO').nth(1).click();
  await page.getByTestId('btn-group-containerNO').nth(2).click();
  await page.getByTestId('btn-group-containerNO').nth(3).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/sa.jpeg');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/sa.jpeg');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/sa.jpeg');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.locator('input[type="file"]').first().setInputFiles('uploads/sa.jpeg');
  await page.getByRole('button', { name: 'Submit Application' }).click();
  await page.getByRole('button', { name: 'Submit Form' }).click();

  await page.waitForTimeout(3000);
  console.log(`✓ Applicant submitted successfully: ${firstName} ${lastName}`);
});