import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev.heims.ph/admission');
  await page.locator('div').filter({ hasText: /^CPTE \(Continuing Professional Teacher Education\)$/ }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('Allan');
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Ger');
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill('C');
  await page.locator('#civil_status').click();
  await page.getByRole('option', { name: 'Single' }).click();
  await page.locator('.MuiInputBase-root.MuiFilledInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.MuiInputBase-adornedEnd').click();
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.getByRole('gridcell', { name: '3', exact: true }).click();
  await page.getByRole('textbox', { name: 'Place of Birth' }).click();
  await page.getByRole('textbox', { name: 'Place of Birth' }).fill('a');
  await page.getByText('Male', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Religion' }).click();
  await page.getByRole('textbox', { name: 'Religion' }).fill('NA');
  await page.getByRole('textbox', { name: 'Ethnic Affiliation' }).click();
  await page.getByRole('textbox', { name: 'Ethnic Affiliation' }).fill('NA');
  await page.getByRole('textbox', { name: 'Nationality' }).click();
  await page.getByRole('textbox', { name: 'Nationality' }).fill('NA');
  await page.locator('#region').click();
  await page.getByRole('option', { name: 'REGION XIII (Caraga)' }).click();
  await page.locator('#province').click();
  await page.getByRole('option', { name: 'DINAGAT ISLANDS' }).click();
  await page.locator('#city').click();
  await page.getByRole('option', { name: 'TUBAJON' }).click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'Santa Cruz (Pob.)' }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).fill('a');
  await page.getByRole('textbox', { name: 'Telephone Number' }).click();
  await page.getByRole('textbox', { name: 'Telephone Number' }).fill('a');
  await page.getByRole('textbox', { name: 'Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).fill('09915615330');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('ralph.prosolutions@gmail.com');
  await page.getByText('Email Address').click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByText('YesNo').first().click();
  await page.getByTestId('btn-group-containerNO').first().click();
  await page.getByTestId('btn-group-containerNO').nth(2).click();
  await page.getByTestId('btn-group-containerNO').nth(1).click();
  await page.getByTestId('btn-group-containerNO').nth(3).click();
  await page.getByTestId('btn-group-containerNO').nth(4).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.locator('#classification').click();
  await page.getByRole('option', { name: 'Masteral' }).click();
  await page.getByRole('combobox', { name: 'Continuing Professional' }).click();
  await page.locator('.MuiBackdrop-root').dblclick();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Add School' }).click();
  await page.getByRole('textbox', { name: 'School Name' }).click();
  await page.getByRole('textbox', { name: 'School Name' }).fill('sample school');
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'Master Degree' }).click();
  await page.getByRole('textbox', { name: 'Program' }).click();
  await page.getByRole('textbox', { name: 'Program' }).fill('sample program');
  await page.getByRole('textbox', { name: 'Graduation Year' }).click();
  await page.getByRole('textbox', { name: 'Graduation Year' }).fill('2025');
  await page.getByRole('textbox', { name: 'GWA' }).click();
  await page.getByRole('textbox', { name: 'GWA' }).fill('90');
  await page.getByRole('button', { name: 'Add School' }).click();
  await page.getByText('Educational BackgroundLast').click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('textbox', { name: 'Complete Name' }).click();
  await page.getByRole('textbox', { name: 'Complete Name' }).fill('sample');
  await page.getByRole('textbox', { name: 'Complete Address' }).click();
  await page.getByRole('textbox', { name: 'Complete Address' }).fill('a');
  await page.getByRole('textbox', { name: 'Telephone Number' }).click();
  await page.getByRole('textbox', { name: 'Telephone Number' }).fill('a');
  await page.getByRole('textbox', { name: 'Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).fill('a');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('sample@gmail.com');
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('heading', { name: 'Consent for Medical Treatment' }).click();
  await page.getByRole('radio', { name: 'I consent to the University Infirmary providing medical treatment in case of' }).check();
  await page.getByRole('radio', { name: 'I consent to the University Infirmary giving medications appropriate for my' }).check();
  await page.getByRole('radio', { name: 'No Yes' }).first().check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(1).check();
  await page.locator('div').filter({ hasText: /^No$/ }).nth(2).click();
  await page.getByRole('radio', { name: 'No Yes' }).nth(2).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(3).check();
  await page.getByRole('radio', { name: 'No Yes' }).nth(4).check();
  await page.getByTestId('btn-group-containerNO').first().click();
  await page.getByTestId('btn-group-containerNO').nth(1).click();
  await page.getByTestId('btn-group-containerNO').nth(2).click();
  await page.getByTestId('btn-group-containerYES').nth(3).click();
  await page.getByRole('radio', { name: 'No Yes' }).nth(5).check();
  await page.locator('#do_alcohol').first().check();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.getByRole('button', { name: 'Browse' }).first().setInputFiles('advising slip.png');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.getByRole('button', { name: 'Browse' }).first().setInputFiles('advising slip.png');
  await page.getByRole('button', { name: 'Browse' }).first().click();
  await page.getByRole('button', { name: 'Browse' }).first().setInputFiles('advising slip.png');
  await page.getByRole('button', { name: 'Browse' }).click();
  await page.getByRole('button', { name: 'Browse' }).setInputFiles('advising slip.png');
  await page.getByRole('button', { name: 'Submit Application' }).click();
  await page.getByRole('button', { name: 'Submit Form' }).click();
});